import { User, Business, Agent, Call, PhoneNumber, Campaign, KnowledgeItem, IntegrationItem, Plan } from '../types';

export const mockCurrentUser: User = {
  id: 'usr_shailesh_99',
  name: 'Shailesh',
  email: 'shailesh@apolloclinics.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  role: 'owner',
  businessId: 'biz_apollo_01',
};

export const mockBusinesses: Business[] = [
  {
    id: 'biz_apollo_01',
    name: 'Apollo Clinics',
    slug: 'apollo-clinics',
    industry: 'Healthcare',
    planId: 'business',
    phone: '+91 80 4719 3200',
    timezone: 'Asia/Kolkata (IST)',
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'biz_fitzone_02',
    name: 'FitZone Global',
    slug: 'fitzone-global',
    industry: 'Fitness & Wellness',
    planId: 'growth',
    phone: '+1 (800) 555-0199',
    timezone: 'America/New_York (EST)',
    createdAt: '2026-02-10T10:30:00Z',
  },
  {
    id: 'biz_rise_03',
    name: 'Rise Realty',
    slug: 'rise-realty',
    industry: 'Real Estate',
    planId: 'enterprise',
    phone: '+1 (415) 890-4321',
    timezone: 'America/Los_Angeles (PST)',
    createdAt: '2025-11-20T14:15:00Z',
  },
];

export const mockAgents: Agent[] = [
  {
    id: 'ag_receptionist_01',
    businessId: 'biz_apollo_01',
    name: 'Receptionist',
    description: 'Handles incoming clinic inquiries, answers patient questions, and schedules appointments.',
    industry: 'Healthcare',
    type: 'receptionist',
    voiceId: 'ava_natural',
    voiceName: 'Ava (Natural)',
    language: 'English (US)',
    speed: 1.0,
    pitch: 1.0,
    status: 'active',
    callsCount: 412,
    minutesUsed: 280,
    createdAt: '2026-03-01T09:00:00Z',
    instructions: {
      role: 'Head Front-Desk Receptionist at Apollo Clinics',
      personality: 'Warm, calm, empathetic, and exceptionally professional.',
      objectives: 'Welcome callers, answer clinic hours/pricing, qualify emergency vs routine cases, and book doctor consultations.',
      rules: 'Never give definitive prescription advice; advise urgent ER visit for severe chest pain or shortness of breath.',
      greeting: 'Thank you for calling Apollo Clinics! My name is Ava. How can I assist you with your health and scheduling today?',
      fallback: 'I want to make sure you get exact information. Let me connect you directly to our lead clinical coordinator.',
    },
    tools: {
      calendarBooking: true,
      crmSync: true,
      callTransfer: true,
      smsFollowup: true,
      transferNumber: '+91 80 4719 3205',
    },
    knowledgeBaseIds: ['kb_clinic_hours', 'kb_doctor_profiles', 'kb_insurance_faq'],
    provider: 'OmniDimension',
    providerAgentId: 'omni_ag_recep_8849',
  },
  {
    id: 'ag_sales_02',
    businessId: 'biz_apollo_01',
    name: 'Sales Agent',
    description: 'Qualifies prospective corporate health plans, wellness packages, and executive screenings.',
    industry: 'Healthcare',
    type: 'sales',
    voiceId: 'liam_warm',
    voiceName: 'Liam (Warm)',
    language: 'English (US)',
    speed: 1.05,
    pitch: 0.95,
    status: 'active',
    callsCount: 348,
    minutesUsed: 290,
    createdAt: '2026-03-05T11:00:00Z',
    instructions: {
      role: 'Senior Corporate Wellness Advisor',
      personality: 'Consultative, engaging, knowledgeable, confident.',
      objectives: 'Understand organization size, current health plans, budget, and book high-value corporate demos.',
      rules: 'Focus on ROI, employee satisfaction, and customized preventive screening programs.',
      greeting: 'Hello! This is Liam with Apollo Wellness Solutions. Are you exploring employee health checkup programs this quarter?',
      fallback: 'Let me email you our comprehensive corporate tier deck and introduce you to our VP of Partnerships.',
    },
    tools: {
      calendarBooking: true,
      crmSync: true,
      callTransfer: true,
      smsFollowup: true,
    },
    knowledgeBaseIds: ['kb_pricing_tiers', 'kb_corporate_wellness'],
    provider: 'OmniDimension',
    providerAgentId: 'omni_ag_sales_1120',
  },
  {
    id: 'ag_support_03',
    businessId: 'biz_apollo_01',
    name: 'Support Agent',
    description: 'Assists patients with portal logins, lab report availability, and general inquiries.',
    industry: 'Healthcare',
    type: 'support',
    voiceId: 'sophia_soft',
    voiceName: 'Sophia (Soft)',
    language: 'English (US)',
    speed: 0.95,
    pitch: 1.05,
    status: 'active',
    callsCount: 310,
    minutesUsed: 195,
    createdAt: '2026-03-08T14:30:00Z',
    instructions: {
      role: 'Patient Care & Support Specialist',
      personality: 'Gentle, patient, reassuring, and meticulous.',
      objectives: 'Resolve patient portal access questions, track test report release timelines, and guide billing payments.',
      rules: 'Always verify date of birth and patient ID before releasing test delivery status.',
      greeting: 'Good day, you have reached Apollo Patient Care. My name is Sophia. How may I support you today?',
      fallback: 'I will open a high-priority ticket with our laboratory team immediately and text you the reference number.',
    },
    tools: {
      calendarBooking: false,
      crmSync: true,
      callTransfer: true,
      smsFollowup: true,
    },
    knowledgeBaseIds: ['kb_patient_portal', 'kb_insurance_faq'],
    provider: 'OmniDimension',
    providerAgentId: 'omni_ag_supp_3391',
  },
  {
    id: 'ag_campaign_04',
    businessId: 'biz_apollo_01',
    name: 'Campaign Agent',
    description: 'Outbound voice agent for seasonal vaccine reminders and routine preventive follow-ups.',
    industry: 'Healthcare',
    type: 'custom',
    voiceId: 'oliver_energetic',
    voiceName: 'Oliver (Crisp)',
    language: 'English (US)',
    speed: 1.0,
    pitch: 1.0,
    status: 'paused',
    callsCount: 178,
    minutesUsed: 80,
    createdAt: '2026-03-12T16:00:00Z',
    instructions: {
      role: 'Preventive Health Outreach Ambassador',
      personality: 'Friendly, concise, and respectful of patient time.',
      objectives: 'Remind registered patients of their bi-annual health screenings and schedule one-click slots.',
      rules: 'Do not pressure callers; always offer an opt-out or SMS recap.',
      greeting: 'Hi there! This is Oliver calling from Apollo Clinics with a quick friendly checkup on your annual health review.',
      fallback: 'No worries at all! I can send you a secure scheduling link via text message if you prefer.',
    },
    tools: {
      calendarBooking: true,
      crmSync: true,
      callTransfer: false,
      smsFollowup: true,
    },
    knowledgeBaseIds: ['kb_doctor_profiles'],
    provider: 'OmniDimension',
    providerAgentId: 'omni_ag_camp_9921',
  },
];

export const mockCalls: Call[] = [
  {
    id: 'call_01',
    businessId: 'biz_apollo_01',
    callerNumber: '+91 98765 43210',
    callerName: 'Rajesh Sharma',
    agentId: 'ag_receptionist_01',
    agentName: 'Receptionist',
    direction: 'inbound',
    status: 'answered',
    durationSeconds: 134,
    durationFormatted: '02:14',
    timestamp: 'Sep 19, 10:24 AM',
    sentiment: 'positive',
    transcript: [
      { speaker: 'agent', text: 'Thank you for calling Apollo Clinics! My name is Ava. How can I assist you with your health and scheduling today?', timestamp: '00:02' },
      { speaker: 'caller', text: 'Hi Ava, I need to book a general checkup with Dr. Mehta for this Friday afternoon.', timestamp: '00:08' },
      { speaker: 'agent', text: 'I would be happy to help with that! Dr. Rohan Mehta has availability this Friday at 2:30 PM or 4:00 PM. Which one suits you better?', timestamp: '00:15' },
      { speaker: 'caller', text: '4:00 PM works perfect for me.', timestamp: '00:21' },
      { speaker: 'agent', text: 'Excellent. I have reserved Friday at 4:00 PM with Dr. Mehta under your registered number. You will receive an SMS confirmation in a few moments. Is there anything else I can help with?', timestamp: '00:32' },
      { speaker: 'caller', text: 'That is all. Thank you very much!', timestamp: '00:36' },
      { speaker: 'agent', text: 'You are most welcome. Have a wonderful and healthy day!', timestamp: '00:40' },
    ],
    extractedEntities: {
      appointmentRequested: true,
      appointmentTime: 'Friday, Sep 22, 4:00 PM',
      intent: 'Doctor Consultation Booking',
      leadScore: 92,
      notes: 'Booked Dr. Rohan Mehta consultation. Confirmation SMS dispatched.',
    },
    providerCallId: 'omni_c_8921a',
  },
  {
    id: 'call_02',
    businessId: 'biz_apollo_01',
    callerNumber: '+91 91234 56789',
    callerName: 'Priya Nambiar',
    agentId: 'ag_support_03',
    agentName: 'Support Agent',
    direction: 'inbound',
    status: 'answered',
    durationSeconds: 272,
    durationFormatted: '04:32',
    timestamp: 'Sep 19, 09:11 AM',
    sentiment: 'positive',
    transcript: [
      { speaker: 'agent', text: 'Good morning, you have reached Apollo Patient Care. My name is Sophia. How may I support you today?', timestamp: '00:02' },
      { speaker: 'caller', text: 'Hello, I had my blood work done on Tuesday, and I wanted to know when my digital lipid panel report will be available on the portal.', timestamp: '00:11' },
      { speaker: 'agent', text: 'I can certainly check that status for you right away. May I verify your registered date of birth for patient privacy?', timestamp: '00:20' },
      { speaker: 'caller', text: 'Yes, it is October 14, 1988.', timestamp: '00:26' },
      { speaker: 'agent', text: 'Thank you! Your lipid panel results have been signed off by the pathologist this morning. I have just authorized immediate notification so you can view it directly in the Apollo Health app.', timestamp: '00:42' },
      { speaker: 'caller', text: 'Wonderful, I see the notification just arrived on my phone. Thank you Sophia!', timestamp: '00:54' },
      { speaker: 'agent', text: 'You are so welcome! Please take care and reach back if you need any further assistance.', timestamp: '01:00' },
    ],
    extractedEntities: {
      appointmentRequested: false,
      intent: 'Lab Report Verification',
      leadScore: 70,
      notes: 'Patient verified DOB. Lipid panel verified and pushed to mobile app.',
    },
    providerCallId: 'omni_c_7731b',
  },
  {
    id: 'call_03',
    businessId: 'biz_apollo_01',
    callerNumber: '+91 99687 66554',
    callerName: 'Sunil Verma',
    agentId: 'ag_sales_02',
    agentName: 'Sales Agent',
    direction: 'inbound',
    status: 'missed',
    durationSeconds: 0,
    durationFormatted: '—',
    timestamp: 'Sep 18, 08:45 PM',
    sentiment: 'neutral',
    transcript: [],
    extractedEntities: {
      intent: 'After-hours inbound call inquiry',
      notes: 'Automated SMS callback trigger queued for 9:00 AM next morning.',
    },
    providerCallId: 'omni_c_miss_339',
  },
  {
    id: 'call_04',
    businessId: 'biz_apollo_01',
    callerNumber: '+91 90011 22334',
    callerName: 'Ananya Reddy',
    agentId: 'ag_receptionist_01',
    agentName: 'Receptionist',
    direction: 'inbound',
    status: 'answered',
    durationSeconds: 69,
    durationFormatted: '01:09',
    timestamp: 'Sep 18, 06:21 PM',
    sentiment: 'positive',
    transcript: [
      { speaker: 'agent', text: 'Thank you for calling Apollo Clinics! My name is Ava. How can I assist you?', timestamp: '00:02' },
      { speaker: 'caller', text: 'Hi! Could you tell me what time the diagnostic imaging wing closes today?', timestamp: '00:08' },
      { speaker: 'agent', text: 'Our diagnostic and X-ray imaging wing is open until 8:00 PM this evening. Walk-in appointments are accepted until 7:30 PM.', timestamp: '00:18' },
      { speaker: 'caller', text: 'Super, I will come by in twenty minutes. Thank you!', timestamp: '00:24' },
      { speaker: 'agent', text: 'You are welcome, see you shortly!', timestamp: '00:27' },
    ],
    extractedEntities: {
      intent: 'Clinic Timings Inquiry',
      leadScore: 65,
      notes: 'Imaging wing timings provided. Expected walk-in.',
    },
    providerCallId: 'omni_c_1194c',
  },
  {
    id: 'call_05',
    businessId: 'biz_apollo_01',
    callerNumber: '+91 98712 33445',
    callerName: 'Deepak Chopra',
    agentId: 'ag_campaign_04',
    agentName: 'Campaign Agent',
    direction: 'outbound',
    status: 'answered',
    durationSeconds: 207,
    durationFormatted: '03:27',
    timestamp: 'Sep 18, 04:18 PM',
    sentiment: 'positive',
    transcript: [
      { speaker: 'agent', text: 'Hello Deepak, this is Oliver calling from Apollo Clinics. I hope your week is going well!', timestamp: '00:03' },
      { speaker: 'caller', text: 'Yes, hi Oliver. What is this regarding?', timestamp: '00:07' },
      { speaker: 'agent', text: 'Our system noted that your complimentary annual health checkup is due this month under your corporate wellness membership. We are currently booking weekend slots for member convenience.', timestamp: '00:19' },
      { speaker: 'caller', text: 'Oh that is right! Do you have Sunday morning available?', timestamp: '00:25' },
      { speaker: 'agent', text: 'Yes, Sunday at 9:30 AM is open at our Indiranagar center. Shall I lock that in for you?', timestamp: '00:34' },
      { speaker: 'caller', text: 'Yes please, that would be ideal.', timestamp: '00:38' },
      { speaker: 'agent', text: 'Wonderful. Your appointment is confirmed, and a pre-fasting guideline is on its way to your WhatsApp and SMS.', timestamp: '00:48' },
    ],
    extractedEntities: {
      appointmentRequested: true,
      appointmentTime: 'Sunday, Sep 24, 9:30 AM',
      intent: 'Outbound Annual Wellness Recall',
      leadScore: 95,
      notes: 'Outbound campaign successful. Indiranagar center slot booked.',
    },
    providerCallId: 'omni_c_5542d',
  },
];

export const mockCallActivityData = [
  { date: 'Sep 13', answered: 145, missed: 18, total: 163 },
  { date: 'Sep 14', answered: 168, missed: 22, total: 190 },
  { date: 'Sep 15', answered: 152, missed: 15, total: 167 },
  { date: 'Sep 16', answered: 188, missed: 28, total: 216 },
  { date: 'Sep 17', answered: 210, missed: 19, total: 229 },
  { date: 'Sep 18', answered: 162, missed: 24, total: 186 },
  { date: 'Sep 19', answered: 195, missed: 12, total: 207 },
];

export const mockPhoneNumbers: PhoneNumber[] = [
  {
    id: 'phone_01',
    businessId: 'biz_apollo_01',
    number: '+91 80 4719 3200',
    country: 'IN',
    friendlyName: 'Apollo Main Hospital Line',
    assignedAgentId: 'ag_receptionist_01',
    assignedAgentName: 'Receptionist',
    status: 'active',
    direction: 'both',
    provider: 'OmniDimension',
    monthlyCost: 15,
  },
  {
    id: 'phone_02',
    businessId: 'biz_apollo_01',
    number: '+1 (800) 459-2874',
    country: 'US',
    friendlyName: 'Toll-Free Health Desk',
    assignedAgentId: 'ag_support_03',
    assignedAgentName: 'Support Agent',
    status: 'active',
    direction: 'inbound',
    provider: 'OmniDimension',
    monthlyCost: 20,
  },
  {
    id: 'phone_03',
    businessId: 'biz_apollo_01',
    number: '+91 80 4719 3288',
    country: 'IN',
    friendlyName: 'Corporate Wellness Outbound',
    assignedAgentId: 'ag_campaign_04',
    assignedAgentName: 'Campaign Agent',
    status: 'active',
    direction: 'outbound',
    provider: 'OmniDimension',
    monthlyCost: 15,
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp_01',
    businessId: 'biz_apollo_01',
    name: 'Flu Vaccine & Senior Care Outreach',
    agentId: 'ag_campaign_04',
    agentName: 'Campaign Agent',
    status: 'running',
    totalContacts: 450,
    completedContacts: 312,
    answeredContacts: 284,
    failedContacts: 28,
    scheduleTime: 'Mon - Fri, 10:00 AM - 6:00 PM',
    minutesUsed: 498,
    createdAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'camp_02',
    businessId: 'biz_apollo_01',
    name: 'Executive Health Checkup Follow-up',
    agentId: 'ag_sales_02',
    agentName: 'Sales Agent',
    status: 'completed',
    totalContacts: 200,
    completedContacts: 200,
    answeredContacts: 182,
    failedContacts: 18,
    scheduleTime: 'Sep 01 - Sep 10, 2026',
    minutesUsed: 320,
    createdAt: '2026-08-28T09:00:00Z',
  },
];

export const mockKnowledgeItems: KnowledgeItem[] = [
  {
    id: 'kb_clinic_hours',
    businessId: 'biz_apollo_01',
    title: 'Clinic Hours, Locations & Emergency Protocols',
    type: 'document',
    sizeOrCount: '1.2 MB PDF',
    status: 'ready',
    updatedAt: 'Sep 15, 2026',
    assignedAgentIds: ['ag_receptionist_01', 'ag_support_03'],
  },
  {
    id: 'kb_doctor_profiles',
    businessId: 'biz_apollo_01',
    title: 'Doctor Specialists Directory & Weekly Schedules',
    type: 'faq',
    sizeOrCount: '48 FAQs',
    status: 'ready',
    updatedAt: 'Sep 18, 2026',
    assignedAgentIds: ['ag_receptionist_01'],
  },
  {
    id: 'kb_insurance_faq',
    businessId: 'biz_apollo_01',
    title: 'Cashless Insurance & TPA Network Providers',
    type: 'url',
    sizeOrCount: 'https://apolloclinics.com/insurance',
    status: 'ready',
    updatedAt: 'Sep 12, 2026',
    assignedAgentIds: ['ag_receptionist_01', 'ag_support_03', 'ag_sales_02'],
  },
  {
    id: 'kb_pricing_tiers',
    businessId: 'biz_apollo_01',
    title: '2026 Preventive Wellness Packages & Pricing Sheet',
    type: 'document',
    sizeOrCount: '3.4 MB DOCX',
    status: 'ready',
    updatedAt: 'Sep 02, 2026',
    assignedAgentIds: ['ag_sales_02'],
  },
];

export const mockIntegrations: IntegrationItem[] = [
  {
    id: 'int_gcal',
    name: 'Google Calendar',
    category: 'calendar',
    description: 'Direct real-time two-way sync for scheduling consultations, demos, and patient visits.',
    connected: true,
    icon: 'Calendar',
    lastSynced: '2 mins ago',
  },
  {
    id: 'int_hubspot',
    name: 'HubSpot CRM',
    category: 'crm',
    description: 'Auto-log voice calls, transcripts, sentiment scores, and created contacts instantly.',
    connected: true,
    icon: 'Database',
    lastSynced: '15 mins ago',
  },
  {
    id: 'int_salesforce',
    name: 'Salesforce',
    category: 'crm',
    description: 'Enterprise pipeline management with automatic lead qualification recording.',
    connected: false,
    icon: 'Cloud',
  },
  {
    id: 'int_slack',
    name: 'Slack Alerts',
    category: 'communication',
    description: 'Send instant notifications to dedicated channels on missed calls or high-value leads.',
    connected: true,
    icon: 'MessageSquare',
    lastSynced: 'Just now',
  },
  {
    id: 'int_razorpay',
    name: 'Razorpay Payments',
    category: 'payments',
    description: 'Seamless subscription billing and usage fee collection powered by Razorpay.',
    connected: true,
    icon: 'CreditCard',
    lastSynced: 'Today',
  },
  {
    id: 'int_webhook',
    name: 'Custom Webhooks',
    category: 'webhooks',
    description: 'Receive signed HTTPS payloads on call.started, call.completed, and appointment.created.',
    connected: true,
    icon: 'Webhook',
    lastSynced: 'Active listener',
  },
];

export const mockPlans: Plan[] = [
  {
    id: 'starter',
    name: 'Starter',
    priceMonthly: 49,
    priceYearly: 39,
    minutesIncluded: 250,
    agentsLimit: 2,
    phoneNumbersLimit: 1,
    description: 'Ideal for local businesses and solo practices automating front-desk calls.',
    features: [
      '250 Inbound & Outbound minutes',
      '2 Custom AI Voice Agents',
      '1 Dedicated Phone Number',
      'Standard Voice Latency (<450ms)',
      'Calendar appointment scheduling',
      'Basic Call Logs & Transcripts',
      'Email & Community Support',
    ],
  },
  {
    id: 'growth',
    name: 'Growth',
    priceMonthly: 149,
    priceYearly: 119,
    minutesIncluded: 1000,
    agentsLimit: 5,
    phoneNumbersLimit: 3,
    description: 'For growing clinics, agencies, and real estate teams with steady call volume.',
    features: [
      '1,000 Inbound & Outbound minutes',
      '5 Custom AI Voice Agents',
      '3 Dedicated Phone Numbers',
      'Ultra-low Latency (<350ms)',
      'CRM sync (HubSpot & Salesforce)',
      'Custom Knowledge Base (10 docs/URLs)',
      'Outbound Calling Campaigns',
      'Priority Support',
    ],
  },
  {
    id: 'business',
    name: 'Business',
    popular: true,
    priceMonthly: 399,
    priceYearly: 319,
    minutesIncluded: 3000,
    agentsLimit: 15,
    phoneNumbersLimit: 10,
    description: 'For multi-location practices, busy dealerships, and customer support hubs.',
    features: [
      '3,000 Inbound & Outbound minutes',
      '15 Custom AI Voice Agents',
      '10 Dedicated Phone Numbers',
      'Lowest Latency Tier (<280ms)',
      'Full Multi-tenant Team RBAC',
      'OmniDimension Direct Trunking',
      'Unlimited Knowledge Base documents',
      'Custom Webhooks & REST API access',
      'Dedicated Account Manager',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    priceMonthly: 999,
    priceYearly: 799,
    minutesIncluded: 10000,
    agentsLimit: 999,
    phoneNumbersLimit: 50,
    description: 'Tailored infrastructure, custom fine-tuned voice models, and SLA guarantees.',
    features: [
      '10,000+ Custom Minutes pool',
      'Unlimited AI Voice Agents',
      'Dedicated SIP trunks & local numbers',
      'Custom Voice Cloning & Tone Design',
      'Self-hosted or Hybrid Deployment',
      'HIPAA / SOC2 Compliance packages',
      '24/7 Dedicated SLA with <15m response',
    ],
  },
];

export const mockScheduledCalls = [
  {
    id: 'sc_01',
    businessId: 'biz_apollo_01',
    customerName: 'Meera Krishnan',
    customerPhone: '+91 98450 11223',
    customerEmail: 'meera.k@gmail.com',
    agentId: 'ag_receptionist_01',
    agentName: 'Ava - Clinic Receptionist',
    scheduledAt: new Date(Date.now() + 3600000 * 2).toISOString(),
    timezone: 'Asia/Kolkata (IST)',
    purpose: 'Cardiology Follow-Up & ECG Scheduling',
    status: 'scheduled' as const,
    priority: 'high' as const,
    notes: 'Patient requested Dr. Mehta OPD slot. Fasting lipid panel reminder needed.',
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sc_02',
    businessId: 'biz_apollo_01',
    customerName: 'Anand Sundaram',
    customerPhone: '+91 97412 88990',
    customerEmail: 'anand.s@infosys.com',
    agentId: 'ag_sales_02',
    agentName: 'Liam - Corporate Health Advisor',
    scheduledAt: new Date(Date.now() + 3600000 * 5).toISOString(),
    timezone: 'Asia/Kolkata (IST)',
    purpose: 'Executive Annual Health Checkup Plan Review',
    status: 'scheduled' as const,
    priority: 'medium' as const,
    notes: 'Interested in Platinum Corporate Health Tier for 85 team members.',
    retryCount: 0,
    maxRetries: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sc_03',
    businessId: 'biz_apollo_01',
    customerName: 'Vikram Joshi',
    customerPhone: '+91 99001 44556',
    customerEmail: 'vikram.j@gmail.com',
    agentId: 'ag_campaign_04',
    agentName: 'Oliver - Preventive Health Recall',
    scheduledAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    timezone: 'Asia/Kolkata (IST)',
    purpose: 'Senior Citizen Flu Vaccination Drive',
    status: 'completed' as const,
    priority: 'medium' as const,
    notes: 'Successfully scheduled for Saturday 11:30 AM with Dr. Sen.',
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    callOutcome: 'Appointment Booked',
    simulatedDuration: 148,
  },
  {
    id: 'sc_04',
    businessId: 'biz_apollo_01',
    customerName: 'Sunita Reddy',
    customerPhone: '+91 98860 33442',
    customerEmail: 'sunita.reddy@techm.com',
    agentId: 'ag_support_03',
    agentName: 'Sophia - Patient Support Desk',
    scheduledAt: new Date(Date.now() + 3600000 * 24).toISOString(),
    timezone: 'Asia/Kolkata (IST)',
    purpose: 'MRI Diagnostic Report Doctor Consultation',
    status: 'scheduled' as const,
    priority: 'urgent' as const,
    notes: 'Urgent spine MRI report review requested before international travel.',
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date().toISOString(),
  },
];

